### PR TITLE
Add colors to address bar

### PR DESCRIPTION
**Pull request by DJDavid98**
This pull request is a resubmission of #18 as [requested](https://github.com/MicrosoftEdge/JSBrowser/pull/18#issuecomment-157450012) by @jdalton, see original pull request for previous discussion.

### CODE REVIEW

**Comment by jdalton** [comment]
Rock!

**Comment by jayrenn** [comment]
@DJDavid98 We resubmitted the app to the Store with your changes. Hopefully it should be updated after the weekend!

**Comment by DJDavid98** [comment]
@jayrenn Where is this app in the Store? A search for "JSBrowser" shows no results on my Windows 10.

**Comment by jayrenn** [comment]
It's listed as [JavaScript Browser](https://www.microsoft.com/store/apps/9NBLGGH1Z7VX).

**Comment by DJDavid98** [comment]
@jayrenn Oh, thanks!

**Pull request merged**
