### PR TITLE
Fix minor mobile issues (#19 & #20)

### PR DESCRIPTION
**Pull request by filfat**
Re-submitted as requested ;)

### CODE REVIEW

**Comment by jdalton** [comment]
Related to #20.

**Comment by filfat** [comment]
also related to #19.

**Comment by filfat** [comment]
Fixed merge conflicts.

**Comment by filfat** [comment]
@jdalton LGTM?

**Comment by jdalton** [comment]
Hi @filfat, sorry I haven't gotten to review this yet. I'll try to merge this in asap.

**Pull request merged**
